### PR TITLE
Cleaner README.md

### PR DESCRIPTION
**Pull request by JordanViknar**
The README.md was messy, so I simply cleaned it and made it more readable.

(I intend to try your application later, and check if it also works on Linux, since I don't use Windows. If it doesn't, I might make another fork followed by a Pull Request.)

### CODE REVIEW

**Comment by JordanViknar** [comment]
This is a draft because I want to take some time later to confirm I did not make any mistake before merging.

**Comment by KillerBOSS2019** [comment]
Alright just so you know I am working on a rework. because as right now the GUI when you click a button it will connect to headphone and then disconnect I wanted to make it so the connection always open until the APP is closed

**Comment by KillerBOSS2019** [comment]
And also add a EQ settings :D 
image

**Comment by JordanViknar** [comment]
I think the README.md is close to done. I'll have to check one last time for good when I can, and then I'll set this pull request as "Ready for review".

**Comment by JordanViknar** [comment]
The only thing left to do is add a note that you need Python installed (obviously) and also Tkinter installed (slightly less obvious). As for the application, I didn't manage to start it on my system, but I was using the Wayland windowing system, and I suspect that Tkinter doesn't support it well (yet ?). I'll try again with X11/Xorg's windowing system later.

**Comment by JordanViknar** [comment]
The API also fully works under Linux. The application is incompatible with Wayland (even with XWayland in my case, which is unexpected), but does work properly under X11/Xorg, which is the default for most Desktop Environments anyways.

**Comment by JordanViknar** [comment]
Took me more time than it should have, but I've opened the Pull Request.

**Comment by KillerBOSS2019** [comment]
Thank you! I've also update the API and reworked the Desktop app

**Pull request merged**
